language: ruby
notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - axlsx@googlegroups.com
    on_success: always
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-1.6.6
  - jruby-1.6.7
  - jruby-18mode
  - jruby-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head