language: ruby
notifications:
  irc: "irc.freenode.org#axlsx"
  email:
    recipients:
      - digital.ipseity@gmail.com
    on_success: always
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: ruby-head