language: ruby

notifications:
  irc: "irc.freenode.org#axlsx"
  email: "digital.ipseity@gmail.com"

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-head
  - jruby-18mode

matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: ruby-head
    - rvm: jruby-head

