notifications:
  irc: "irc.freenode.org#axlsx"
  email: "digital.ipeseity@gmail.com"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    rvm:
      - jruby
      - ruby-head
      - jruby-head

